mongo:
  image: mongo:3.0
  command: mongod --smallfiles
  ports:
    - 27017:27017

test:
  image: node:0.12.7-onbuild
  command: npm run test
  volumes:
    - .:/usr/src/app
  environment:
    MONGO_DATABASE: game-service-test
    THEMOVIEDB_API_KEY: # get env with same name from host
  links:
    - mongo:mongo
