mongo:
  image: mongo:2.6
  command: mongod --smallfiles
  ports:
    - 27017:27017

test:
  image: node:0.12.7-onbuild
  command: npm run test
  volumes:
    - .:/usr/src/app
  environment:
    MONGO_DATABASE: game-service-test
  links:
    - mongo:mongo
